### ISSUE TITLE
lazyload报错

### ISSUE THREAD

**Issue by 1374363910** [FuShaoLei/hexo-theme-white#11]
```bash
$ hexo s -g
INFO  Validating config
INFO  Start processing
FATAL {
  err: TypeError: Cannot read property 'open' of undefined
      at Hexo.<anonymous> (D:\Documents\GitHub\Mooonkey\themes\white\scripts\lazyload.js:7:24)
      at Hexo.tryCatcher (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\method.js:15:34)
      at D:\Documents\GitHub\Mooonkey\node_modules\hexo\lib\extend\filter.js:67:52
      at tryCatcher (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\util.js:16:23)
      at Object.gotValue (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\reduce.js:166:18)
      at Object.gotAccum (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\reduce.js:155:25)
      at Object.tryCatcher (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:458:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```
然后我把lazyload.js中的这一行注释掉后
```JavaScript
if (theme.lazyload.open!==true) return;
```
能进入本地预览，但是又出现以下问题
```bash
$ hexo s -g
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR {
  err: OperationalError: D:/Documents/GitHub/Mooonkey/themes/white/source/css/_util/base.styl:2:3
     1| theme-config(config, predef)
     2|   unquote(hexo-config(config) ? hexo-config(config):predef)
  --------^

  TypeError: expected string, ident or literal, but got unit:800px

      at Object.exports.assertString (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\utils.js:234:13)
      at Evaluator.unquote (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\functions\unquote.js:21:9)
      at Evaluator.invokeBuiltin (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:1054:30)
      at Evaluator.visitCall (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:516:16)
      at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
      at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
      at Evaluator.visitExpression (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:644:26)
      at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
      at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
      at Evaluator.eval (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:1238:23)
      at Evaluator.invoke (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:1083:16)
      at Evaluator.invokeFunction (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:1012:15)
      at Evaluator.visitCall (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:522:16)
      at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
      at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
      at Evaluator.visitExpression (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:644:26)
      at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
      at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
      at Evaluator.visitExpression (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:644:26)
      at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
      at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
      at Evaluator.visitCall (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:506:19) {
    cause: Error: D:/Documents/GitHub/Mooonkey/themes/white/source/css/_util/base.styl:2:3
       1| theme-config(config, predef)
       2|   unquote(hexo-config(config) ? hexo-config(config):predef)
    --------^

    TypeError: expected string, ident or literal, but got unit:800px

        at Object.exports.assertString (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\utils.js:234:13)
        at Evaluator.unquote (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\functions\unquote.js:21:9)
        at Evaluator.invokeBuiltin (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:1054:30)
        at Evaluator.visitCall (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:516:16)
        at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
        at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
        at Evaluator.visitExpression (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:644:26)
        at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
        at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
        at Evaluator.eval (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:1238:23)
        at Evaluator.invoke (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:1083:16)
        at Evaluator.invokeFunction (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:1012:15)
        at Evaluator.visitCall (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:522:16)
        at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
        at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
        at Evaluator.visitExpression (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:644:26)
        at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
        at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
        at Evaluator.visitExpression (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:644:26)
        at Evaluator.Visitor.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\index.js:28:40)
        at Evaluator.visit (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:160:18)
        at Evaluator.visitCall (D:\Documents\GitHub\Mooonkey\node_modules\stylus\lib\visitor\evaluator.js:506:19) {
      lineno: 2,
      column: 3,
      filename: 'D:/Documents/GitHub/Mooonkey/themes/white/source/css/_util/base.styl',
      stylusStack: '',
      input: 'theme-config(config, predef)\r\n' +
        '  unquote(hexo-config(config) ? hexo-config(config):predef)'
    },
    isOperational: true,
    lineno: 2,
    column: 3,
    filename: 'D:/Documents/GitHub/Mooonkey/themes/white/source/css/_util/base.styl',
    stylusStack: '',
    input: 'theme-config(config, predef)\r\n' +
      '  unquote(hexo-config(config) ? hexo-config(config):predef)'
  }
} Asset render failed: %s css/white.css
(node:18924) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18924) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:18924) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:18924) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:18924) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:18924) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
Unhandled rejection TypeError: D:\Documents\GitHub\Mooonkey\themes\white\layout\archive.ejs:1
 >> 1| <% if(theme.archive.type === 'img') { %>
    2|     <%- partial('_partial/mode-img') %>
    3| <% } %>
    4| <% if(theme.archive.type === 'simple') { %>

Cannot read property 'type' of undefined
    at eval (D:\Documents\GitHub\Mooonkey\themes\white\layout\archive.ejs:10:25)
    at archive (D:\Documents\GitHub\Mooonkey\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (D:\Documents\GitHub\Mooonkey\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Documents\GitHub\Mooonkey\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Documents\GitHub\Mooonkey\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Documents\GitHub\Mooonkey\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Documents\GitHub\Mooonkey\node_modules\hexo\lib\hexo\router.js:30:5)
    at RouteStream.Readable.read (_stream_readable.js:475:10)
    at resume_ (_stream_readable.js:962:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
配置文件里此次更新的内容，我基本没有改动
麻烦大佬了

**Comment by FuShaoLei** [comment]
好奇怪 ，我从来没用遇到过， 你试试 hexo clean后再hexo g 看看 再一个，我是再hexo 5.0下开发的，可能是因为版本问题？

**Comment by 1374363910** [comment]
我都试过了😂，版本也是5.0，我网上也试着找过类似原因，没结果，我回归老版本了，感觉老版本已经很nice了，很喜欢这种简约，加油哦💪

**Comment by FuShaoLei** [comment]
好吧 照理说下载最新的不会出现任何问题，如果你想用最新版又有无法解决的问题的话，欢迎随时与我联系 我的qq是1563250958
@1374363910

**Comment by fyljp** [comment]
可以尝试检查一下 主题 配置文件里面的
```
#图片懒加载
lazyload:
  open: true #是否开启
```
尝试注释后复现错误
如果复制了配置文件到_data文件夹需要重新添加选项！
